spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football
    username: postgres
    password: 12345678
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update  # ou o modo de sua escolha (validate, update, create, create-drop)
    properties:
      hibernate:
        format_sql: true
  application:
    name: santander-bootcap-2024



